TOPDIR=/uscms_data/d3/aandreas/legacy_limit/monox_fit/monojet/

.PHONY: *

cards:
	bash $(TOPDIR)/scripts/make_cards.sh

printcards:
	cat $(TOPDIR)/scripts/make_cards.sh

diag:
	bash $(TOPDIR)/scripts/diagnostics.sh

printdiag:
	cat $(TOPDIR)/scripts/diagnostics.sh

impacts:
	bash $(TOPDIR)/scripts/impacts.sh

printimpacts:
	cat $(TOPDIR)/scripts/impacts.sh

limits:
	bash $(TOPDIR)/scripts/limits.sh

printlimits:
	cat $(TOPDIR)/scripts/limits.sh